name: Build and Deploy GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "yarn"

            - name: Build
              run: |
                  yarn
                  yarn build
              env:
                  CI: true

            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
